name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: test.Rmd
	  output_format: pdf_document
